version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'  # Hardcoded credentials
      MYSQL_DATABASE: 'nbaoverunders' 
      MYSQL_USER: 'web2' 
      MYSQL_PASSWORD: 'mypassword' # this is not the real password web2 has in MySQL
    ports:
      - '3307:3306' # (host:container)
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount SQL script to seed some records

  app:
    build: .
    container_name: go_app_container
    restart: always
    depends_on:
      - mysql
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=web2
      - DB_PASSWORD=mypassword
      - DB_NAME=nbaoverunders
    command: ["/app/nbaoverunders"]

volumes:
  mysql_data:

# docker compose -f docker-compose.yml up --build
# after changes: docker compose down -v
# separate terminal: mysql -h 127.0.0.1 -P 3307 -u web2 -p