version: "3.8"
services:
  mysql:
    image: mysql
    expose:
      - '3306'
    # needed for testing mysql service independently, but omit for building container with go app
    ports:
      - '3307:3306' # (host:container)
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD} 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    environment: # for validating the connection to MySQL in "entrypoint" below
      DB_HOST: 'mysql'
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    #env_file:
    #  - .env
    depends_on:
      - mysql
    entrypoint:
    - bash
    - -c
    - |
      set -e
      echo 'Waiting for MySQL to be available'
      maxTries=10
      while [ "$$maxTries" -gt 0 ] && ! mysqladmin ping -h "$$DB_HOST" -u"$$DB_USER" -p"$$DB_PASSWORD" --silent; do
          sleep 1
          maxTries=$((maxTries - 1))
      done
      echo
      if [ "$$maxTries" -le 0 ]; then
          echo >&2 'error: unable to contact MySQL after 10 tries'
          exit 1
      fi
      # Run the Go app directly without startup.sh
      exec ./nbaoverunders
    

# docker compose -f docker-compose.yml up --build
# after changes: docker compose down -v
# separate terminal: mysql -h 127.0.0.1 -P 3307 -u web2 -p

# reference: https://www.youtube.com/watch?v=p0n90IUfjp4
# conceptual reference: https://www.youtube.com/watch?v=q9uj1CniRYk